# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [42]:
# your code here
import numpy as np


#### 2. Print your NumPy version.

In [43]:
# your code here
print(np.__version__)

1.26.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [44]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.28317679 0.27588537 0.1376866  0.56532439 0.50642927]
  [0.14231061 0.42663118 0.08563697 0.09262981 0.58234607]
  [0.17725494 0.89761426 0.91754861 0.73166658 0.58546804]]

 [[0.52656507 0.03002403 0.88730022 0.0321306  0.13995175]
  [0.83911318 0.32856657 0.56507929 0.95336958 0.26892832]
  [0.57723446 0.92346239 0.53748069 0.85097129 0.7142832 ]]]


In [45]:
# Method 2
a = np.random.randn(2,3,5)
print(a)

[[[ 1.81143407 -0.02702409 -0.57750773 -0.7091791   0.32537585]
  [-0.75717539  0.22857106  1.27180498  0.90897112 -0.54884345]
  [ 0.29403288 -0.11755529  0.41403447  2.11931249  1.33437242]]

 [[ 2.24886149  0.8761091  -0.86046995 -0.30826182 -0.63833906]
  [-0.90402932  0.11471608  0.90214113 -0.24389577  1.848149  ]
  [-0.72636576  1.63004426 -1.0173425   0.8295099   0.81851098]]]


In [46]:
# Method 3
a = np.random.randint(0,1000,size=(5,2,3))
print(a)

[[[862 819 613]
  [982  47  99]]

 [[119 292 706]
  [984 729 740]]

 [[367 863 606]
  [ 51 692 868]]

 [[646 814 358]
  [910 784 402]]

 [[395 917  44]
  [493 879 208]]]


#### 4. Print *a*.


In [47]:
# your code here
print(a)

[[[862 819 613]
  [982  47  99]]

 [[119 292 706]
  [984 729 740]]

 [[367 863 606]
  [ 51 692 868]]

 [[646 814 358]
  [910 784 402]]

 [[395 917  44]
  [493 879 208]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [48]:
# your code here
b = np.random.choice([1], size=(5,2,3))

#### 6. Print *b*.


In [49]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [50]:
# your code here
print(np.size(a))
print(np.size(b))
if(np.size(a) == np.size(b)):
    print("Yes they have")

30
30
Yes they have


#### 8. Are you able to add *a* and *b*? Why or why not?


In [51]:
# your answer here
added_array = a + b # I save the add of both arrays in one array

print(added_array)

# ValueError: operands could not be broadcast together with shapes (5,2,3) (2,3,5) 
# I cannot do it because they dont have the same shape


[[[863 820 614]
  [983  48 100]]

 [[120 293 707]
  [985 730 741]]

 [[368 864 607]
  [ 52 693 869]]

 [[647 815 359]
  [911 785 403]]

 [[396 918  45]
  [494 880 209]]]


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [58]:
# your code here
c =  b.reshape(2,3,5)
c = c.transpose()

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [59]:
# your code/answer here

d = a + c # I save the add of both arrays in one array

print(added_array)

ValueError: operands could not be broadcast together with shapes (5,2,3) (5,3,2) 

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [ ]:
# your code/answer here

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [ ]:
# your code here

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
# your code here

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here