# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [76]:
# your code here
import numpy as np


#### 2. Print your NumPy version.

In [77]:
# your code here
print(np.__version__)

1.26.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [78]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.76265126 0.63988586 0.41318797 0.28359122 0.22907787]
  [0.31391498 0.60781781 0.72132207 0.14195892 0.61939733]
  [0.1552119  0.58578172 0.08859477 0.59545837 0.49614726]]

 [[0.31441979 0.40874956 0.7316074  0.33724661 0.26422869]
  [0.46961963 0.87985234 0.38868073 0.6165775  0.70266765]
  [0.5533113  0.50734377 0.49378148 0.29278615 0.81420578]]]


In [79]:
# Method 2
a = np.random.randn(2,3,5)
print(a)

[[[ 0.26198588  0.30402922  0.20279441  0.04831559  0.02765641]
  [-0.93306749 -0.74881492  0.11085988  0.07546118  0.66924122]
  [-0.61490196  0.8836238   1.50435551  0.59602993  0.92277399]]

 [[ 0.46295281 -0.81808148  0.28021506  1.3297366   0.45486723]
  [-1.47617544  0.84247071  0.68528918  0.77725244 -0.76103796]
  [-0.59488682 -0.48558033  0.54817752  2.14558977  0.05721198]]]


In [80]:
# Method 3
a = np.random.randint(0,1000,size=(2,3,5))
print(a)

[[[969 944 636 148 843]
  [831 741  12 711 385]
  [486 245  96  95 264]]

 [[906 877  31 657 997]
  [604 826 901 714 859]
  [ 47 254 186 601 371]]]


#### 4. Print *a*.


In [81]:
# your code here
print(a)

[[[969 944 636 148 843]
  [831 741  12 711 385]
  [486 245  96  95 264]]

 [[906 877  31 657 997]
  [604 826 901 714 859]
  [ 47 254 186 601 371]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [82]:
# your code here
b = np.random.choice([1], size=(5,2,3))

#### 6. Print *b*.


In [83]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [84]:
# your code here
print(np.size(a))
print(np.size(b))
if(np.size(a) == np.size(b)):
    print("Yes they have")

30
30
Yes they have


In [85]:
print(a.shape)

(2, 3, 5)


In [86]:
print(b.shape)

(5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [87]:
# your answer here
added_array = a + b # I save the add of both arrays in one array

print(added_array)

# ValueError: operands could not be broadcast together with shapes (5,2,3) (2,3,5) 
# I cannot do it because they dont have the same shape


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [88]:
# your code here
c =  b.reshape(2,3,5) #Its not the transpose, because if we transpose 'c' we would have 3,2,5 shape and it has not the same shape to operate with 'a'
print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [89]:
# your code/answer here

d = a + c # I save the add of both arrays in one array

print(added_array)

[[[505 876 952]
  [877  46 686]]

 [[ 48   1 943]
  [549 259 911]]

 [[405 712 401]
  [277 342  49]]

 [[173 751 566]
  [395 363 441]]

 [[305 746 935]
  [120 118 717]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [90]:
# your code/answer here
print("A: " + str(a))
print("D: " + str(d))

# Both has de same shape, but the main difference is that all 'd' values are 'a' + 1 because before we add 'a' + c and
# 'c' has the same values as 'b'(all the values are 1) and the the same shape as 'a' so if you add 'a' + 'c' you have 'd'



A: [[[969 944 636 148 843]
  [831 741  12 711 385]
  [486 245  96  95 264]]

 [[906 877  31 657 997]
  [604 826 901 714 859]
  [ 47 254 186 601 371]]]
D: [[[970 945 637 149 844]
  [832 742  13 712 386]
  [487 246  97  96 265]]

 [[907 878  32 658 998]
  [605 827 902 715 860]
  [ 48 255 187 602 372]]]


In [91]:
#  

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [92]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [93]:
# your code/answer here
print("A: " + str(a))
print("E: " + str(e))
equal = True
for x in a:
    for y in e:
        if x.all() != y.all():
            equal = False
if equal == True:
    print("Yes, these values are equal")
    print("That`s because all of 'c' values are 1, so 'e' is all the 'a' values multiplied by 1 ")
else:
    print("No, there are not equal")
        

A: [[[969 944 636 148 843]
  [831 741  12 711 385]
  [486 245  96  95 264]]

 [[906 877  31 657 997]
  [604 826 901 714 859]
  [ 47 254 186 601 371]]]
E: [[[969 944 636 148 843]
  [831 741  12 711 385]
  [486 245  96  95 264]]

 [[906 877  31 657 997]
  [604 826 901 714 859]
  [ 47 254 186 601 371]]]
Yes, these values are equal
That`s because all of 'c' values are 1, so 'e' is all the 'a' values multiplied by 1 


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [94]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print("Max of d: " + str(d_max))
print("Min of d: " + str(d_min))
print("Mean of d: " + str(d_mean))

Max of d: 998
Min of d: 13
Mean of d: 542.2333333333333


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [97]:
# your code here
print("D: ")
print(d)
f = np.empty(d.shape) # Here we create an empty array with the same shape as 'd'
print("F: ")
print(f)

D: 
[[[970 945 637 149 844]
  [832 742  13 712 386]
  [487 246  97  96 265]]

 [[907 878  32 658 998]
  [605 827 902 715 860]
  [ 48 255 187 602 372]]]
F: 
[[[0.26198588 0.30402922 0.20279441 0.04831559 0.02765641]
  [0.93306749 0.74881492 0.11085988 0.07546118 0.66924122]
  [0.61490196 0.8836238  1.50435551 0.59602993 0.92277399]]

 [[0.46295281 0.81808148 0.28021506 1.3297366  0.45486723]
  [1.47617544 0.84247071 0.68528918 0.77725244 0.76103796]
  [0.59488682 0.48558033 0.54817752 2.14558977 0.05721198]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [98]:
print(f.shape)

(2, 3, 5)


In [100]:
# your code here
# if d[value] > d_min and d[value] < d_mean: correspondant f[value] = 25
# if d[value] > d_mean and d[value] < d_max: correspondant f[value] = 75
# if d[value] == d_mean --> correspondant f[value] = 50
# if d[value] == d_min --> correspondant f[value] = 0
# if d[value] == d_max --> correspondant f[value] = 100


# We iterate the multidimensional array and we assign each 'f' value in each case
for x in range(2):
    for y in range(3):
        for z in range(5):
            if d[x][y][z] == d_min:
                f[x][y][z] = 0
            if d[x][y][z] == d_max:
                f[x][y][z] = 100
            if d[x][y][z] == d_mean:
                f[x][y][z] = 50
            if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                f[x][y][z] = 25
            if d[x][y][z] > d_mean and d[x][y][z] < d_max:
                f[x][y][z] = 75

                
                
                
                
                


F: 
[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.   0.  75.  25.]
  [ 25.  25.  25.  25.  25.]]

 [[ 75.  75.  25.  75. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  25.  25.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [101]:
# your code here

print("F: ")
print(f)

F: 
[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.   0.  75.  25.]
  [ 25.  25.  25.  25.  25.]]

 [[ 75.  75.  25.  75. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  25.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [107]:
# your code here
f = f.astype(str) # Here we transform the floats into strings 

# Here we change the strings value in each case
for x in range(2):
    for y in range(3):
        for z in range(5):
            if f[x][y][z] == '0.0':
                f[x][y][z] = 'A'
            if f[x][y][z] == '25.0':
                f[x][y][z] = 'B'
            if f[x][y][z] == '50.0':
                f[x][y][z] = 'C'
            if f[x][y][z] == '75.0':
                f[x][y][z] = 'D'
            if f[x][y][z] == '100.0':
                f[x][y][z] = 'E'
                
                
            
            
                

In [108]:
print("F: ")
print(f)

F: 
[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'A' 'D' 'B']
  ['B' 'B' 'B' 'B' 'B']]

 [['D' 'D' 'B' 'D' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'B' 'B' 'D' 'B']]]
